# Generated by Django 3.0.5 on 2020-06-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activity_periods',
        ),
        migrations.AddField(
            model_name='user',
            name='activity_periods',
            field=models.ManyToManyField(to='users.ActivityPeriod'),
        ),
    ]
